### ISSUE TITLE
Nieudana instalacji wtyczki TOYA GO

### ISSUE THREAD

**Issue by tadeuszek** [toyago/kodi#1]
Witam. Podczas instalacji na świeżym KODI wtyczki Toya Go, wyskakuje mi "nieudana instalacja", jaki powód może być tego zjawiska, wcześniej na tym samym systemie i wersji Kodi wszystko instalowało się prawidłowo. Dziękuję i Pozdrawiam.

**Comment by piotrekcrash** [comment]
@tadeuszek repozytorium naprawione. Spróbuj teraz.

**Comment by tadeuszek** [comment]
Stokrotne dzięki, jesteś Wielki !

**Comment by Grzegorz19892108** [comment]
Mam problem z zalogowaniem się do ToyaGo na kodi jest ktoś w stanie pomóc, loguje się tym samym loginem i hasłem co na stronie albo na aplikacji na telefonie i nie mogę się zalogować.

**Comment by Piotreklabaj** [comment]
Witam znowu jest problem z toya go nie działa i niema pełnej listy kanałów pozdrawiam

**Comment by piotrekcrash** [comment]
@Piotreklabaj Najnowsza i ostatnia wersja wtyczki znajduje się pod adresem: https://piotrekcrash.github.io/
Wtyczka nie będzie już wspierana ze względu na brak czasu. Cześć kanałów nie działa ze względu na użycie DRM.
Jeżeli ktoś chce przejąć projekt to nie mam nic przeciwko -> Fork.
